In [2]:
import pandas as pd
import joblib
df = pd.read_csv("../data/cleaned_student_data.csv")
X = df.drop("math_score", axis=1)
X_encoded = pd.get_dummies(X, drop_first=True)

In [3]:
from sklearn.model_selection import train_test_split
y = df["math_score"]
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42
)
X_test.shape

(200, 14)

In [4]:
from sklearn.linear_model import LinearRegression
import joblib
import pandas as pd
loaded_model = joblib.load("../models/linear_regression_model.pkl")
sample_input = X_encoded.iloc[0].values.reshape(1, -1)
prediction = loaded_model.predict(sample_input)
prediction

c:\Users\HIYA LODHA\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([66.11021332])

In [5]:
loaded_model = joblib.load("../models/linear_regression_model.pkl")


In [6]:
import joblib
import pandas as pd
loaded_model = joblib.load("../models/linear_regression_model.pkl")
sample_input = X_encoded.iloc[0].values.reshape(1, -1)
prediction = loaded_model.predict(sample_input)
prediction

c:\Users\HIYA LODHA\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([66.11021332])

In [7]:
sample_input = X_encoded.iloc[[0]]

In [8]:
loaded_model = joblib.load("../models/linear_regression_model.pkl")
prediction = loaded_model.predict(sample_input)
prediction

array([66.11021332])

In [11]:
import pandas as pd

feature_importance = pd.DataFrame({
    "feature": X_encoded.columns,
    "coefficient": loaded_model.coef_
}).sort_values(by="coefficient", ascending=False)

In [12]:
feature_importance.to_csv("../data/feature_importance.csv", index=False)